version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip"
      - "unzip -o terraform.zip"
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/terraform
      - terraform init 
      - terraform validate
      - terraform apply -auto-approve
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/src/front-end
      - npm i
      - npm run build
      - aws s3 sync ./src/front-end/build s3://anna-aws-certification-front-end
      - aws cloudfront create-invalidation --distribution-id "E1MXY79U7EY3UN" --paths '/*'

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*