version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/3.27/terraform_3.27_linux_amd64.zip"
      - "unzip -o terraform.zip"
  pre_build:
    commands:
      - npm i
      - npm run test
  build:
    commands:
      - npm run build
      - cd terraform
      - terraform init 
      - terraform apply -auto-approve

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*